### ISSUE TITLE
assemble-image.sh fails

### ISSUE THREAD

**Issue by mdknaebel** [Prototyped/pikvm-container#2]
assemble-image.sh seems to fail for me. I noticed this because I was trying to build for the non-hdmiusb image (v2-hdmi-rpi4-latest), but then I noticed it fails unmodified as well. 

I then tried modifying it to retrieve the PiKVM image that was available at last push, rather than latest, to no avail. Lastly, I commented-out each block in Dockerfile:13, one at a time, and assemble-image.sh still failed on that line each time.

<pre>sudo ./assemble-image.sh 
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian-security bookworm-security InRelease                                     
Hit:3 https://download.docker.com/linux/debian bookworm InRelease                                           
Hit:4 http://deb.debian.org/debian bookworm-updates InRelease                   
Hit:5 http://archive.raspberrypi.com/debian bookworm InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
22 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  lbzip2
0 upgraded, 1 newly installed, 0 to remove and 22 not upgraded.
Need to get 69.6 kB of archives.
After this operation, 164 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main arm64 lbzip2 arm64 2.5-2.3 [69.6 kB]
Fetched 69.6 kB in 0s (290 kB/s)
Selecting previously unselected package lbzip2.
(Reading database ... 60078 files and directories currently installed.)
Preparing to unpack .../lbzip2_2.5-2.3_arm64.deb ...
Unpacking lbzip2 (2.5-2.3) ...
Setting up lbzip2 (2.5-2.3) ...
Processing triggers for man-db (2.11.2-2) ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  490M  100  490M    0     0  17.3M      0  0:00:28  0:00:28 --:--:-- 18.3M

[+] Building 425.3s (9/9) FINISHED                                                                            docker:default
 => [internal] load build definition from Dockerfile                                                                    0.1s
 => => transferring dockerfile: 1.62kB                                                                                  0.0s
 => [internal] load .dockerignore                                                                                       0.1s
 => => transferring context: 2B                                                                                         0.0s
 => [internal] load build context                                                                                      46.6s
 => => transferring context: 748.89MB                                                                                  46.5s
 => [1/6] ADD pikvm-os.tar.bz2 /                                                                                      372.6s
 => [2/6] COPY 1680x1050.hex /etc/kvmd/tc358743-edid.hex                                                                3.9s
 => [3/6] COPY cleanup-usb-gadget.service /etc/systemd/system/                                                          0.2s
 => [4/6] COPY switch-to-uyvy.service /etc/systemd/system/                                                              0.2s
 => [5/6] COPY override.yaml /etc/kvmd/                                                                                 0.2s
 => ERROR [6/6] RUN set -eu;     for unit in man-db.service man-db.timer sshd.service systemd-networkd.service systemd  1.3s
------                                                                                                                       
 > [6/6] RUN set -eu;     for unit in man-db.service man-db.timer sshd.service systemd-networkd.service systemd-timesyncd.service systemd-network-generator.service systemd-networkd-wait-online.service systemd-networkd.socket rngd.service systemd-resolved.service watchdog.service getty@tty1.service systemd-random-seed.service kvmd-bootconfig.service eth0.network en.network 99-default.link;     do systemctl mask $unit;     done;     for unit in dbus-org.freedesktop.timesync1.service dbus-org.freedesktop.network1.service dbus-org.freedesktop.resolve1.service;     do systemctl disable $unit;     done;     for unit in cleanup-usb-gadget.service kvmd-tc358743.service switch-to-uyvy.service kvmd-janus.service;     do systemctl enable $unit;     done;     kvmd-gencert --do-the-thing;     kvmd-gencert --do-the-thing --vnc;     sed -i '/PIBOOT/d; /PIPST/d; /PIMSD/d' /etc/fstab;     sed -i 's/stderr/\/var\/log\/nginx\/error.log/' /etc/kvmd/nginx/nginx.conf;     curl -fLSo /usr/local/bin/remove-gadget.sh https://raw.githubusercontent.com/larsks/systemd-usb-gadget/7602009806a4b838663d9db75e5e7f35e131d0c7/remove-gadget.sh;     chmod 755 /usr/local/bin/remove-gadget.sh:
0.697 Created symlink /etc/systemd/system/sshd.service → /dev/null.
0.706 Created symlink /etc/systemd/system/systemd-networkd.service → /dev/null.
0.716 Created symlink /etc/systemd/system/systemd-timesyncd.service → /dev/null.
0.726 Created symlink /etc/systemd/system/systemd-network-generator.service → /dev/null.
0.736 Created symlink /etc/systemd/system/systemd-networkd-wait-online.service → /dev/null.
0.745 Created symlink /etc/systemd/system/systemd-networkd.socket → /dev/null.
0.755 Created symlink /etc/systemd/system/rngd.service → /dev/null.
0.765 Created symlink /etc/systemd/system/systemd-resolved.service → /dev/null.
0.774 Created symlink /etc/systemd/system/watchdog.service → /dev/null.
0.784 Created symlink /etc/systemd/system/getty@tty1.service → /dev/null.
0.802 Created symlink /etc/systemd/system/kvmd-bootconfig.service → /dev/null.
0.812 Created symlink /etc/systemd/system/eth0.network.service → /dev/null.
0.822 Created symlink /etc/systemd/system/en.network.service → /dev/null.
0.831 Created symlink /etc/systemd/system/99-default.link.service → /dev/null.
0.845 Unit /etc/systemd/system/systemd-timesyncd.service is masked, ignoring.
0.845 The unit files have no installation config (WantedBy=, RequiredBy=, UpheldBy=,
0.845 Also=, or Alias= settings in the [Install] section, and DefaultInstance= for
0.845 template units). This means they are not meant to be enabled or disabled using systemctl.
0.845  
0.845 Possible reasons for having these kinds of units are:
0.845 • A unit may be statically enabled by being symlinked from another unit's
0.845   .wants/, .requires/, or .upholds/ directory.
0.845 • A unit's purpose may be to act as a helper for some other unit which has
0.845   a requirement dependency on it.
0.845 • A unit may be started when needed via activation (socket, path, timer,
0.845   D-Bus, udev, scripted systemctl call, ...).
0.845 • In case of template units, the unit is meant to be enabled with some
0.845   instance name specified.
0.856 Unit /etc/systemd/system/systemd-networkd.service is masked, ignoring.
0.856 The unit files have no installation config (WantedBy=, RequiredBy=, UpheldBy=,
0.856 Also=, or Alias= settings in the [Install] section, and DefaultInstance= for
0.856 template units). This means they are not meant to be enabled or disabled using systemctl.
0.856  
0.856 Possible reasons for having these kinds of units are:
0.856 • A unit may be statically enabled by being symlinked from another unit's
0.856   .wants/, .requires/, or .upholds/ directory.
0.856 • A unit's purpose may be to act as a helper for some other unit which has
0.856   a requirement dependency on it.
0.856 • A unit may be started when needed via activation (socket, path, timer,
0.856   D-Bus, udev, scripted systemctl call, ...).
0.856 • In case of template units, the unit is meant to be enabled with some
0.856   instance name specified.
0.867 Unit /etc/systemd/system/systemd-resolved.service is masked, ignoring.
0.867 The unit files have no installation config (WantedBy=, RequiredBy=, UpheldBy=,
0.867 Also=, or Alias= settings in the [Install] section, and DefaultInstance= for
0.867 template units). This means they are not meant to be enabled or disabled using systemctl.
0.867  
0.867 Possible reasons for having these kinds of units are:
0.867 • A unit may be statically enabled by being symlinked from another unit's
0.867   .wants/, .requires/, or .upholds/ directory.
0.867 • A unit's purpose may be to act as a helper for some other unit which has
0.867   a requirement dependency on it.
0.867 • A unit may be started when needed via activation (socket, path, timer,
0.867   D-Bus, udev, scripted systemctl call, ...).
0.867 • In case of template units, the unit is meant to be enabled with some
0.867   instance name specified.
0.881 Created symlink /etc/systemd/system/kvmd-otg.service.wants/cleanup-usb-gadget.service → /etc/systemd/system/cleanup-usb-gadget.service.
0.904 Created symlink /etc/systemd/system/kvmd.service.wants/switch-to-uyvy.service → /etc/systemd/system/switch-to-uyvy.service.
0.924 + mkdir -p /etc/kvmd/nginx/ssl
0.929 + rm -f '/etc/kvmd/nginx/ssl/*'
0.934 + cd /etc/kvmd/nginx/ssl
0.935 + openssl ecparam -out server.key -name prime256v1 -genkey
1.025 + openssl req -new -x509 -sha256 -nodes -key server.key -out server.crt -days 3650 -subj /C=RU/ST=Moscow/L=Moscow/O=PiKVM/OU=PiKVM/CN=localhost
1.042 + chown root:kvmd-nginx /etc/kvmd/nginx/ssl/server.crt /etc/kvmd/nginx/ssl/server.key
1.049 + chmod 440 /etc/kvmd/nginx/ssl/server.key
1.053 + chmod 444 /etc/kvmd/nginx/ssl/server.crt
1.056 + chmod 755 /etc/kvmd/nginx/ssl
1.064 + mkdir -p /etc/kvmd/vnc/ssl
1.067 + rm -f '/etc/kvmd/vnc/ssl/*'
1.069 + cd /etc/kvmd/vnc/ssl
1.069 + openssl ecparam -out server.key -name prime256v1 -genkey
1.081 + openssl req -new -x509 -sha256 -nodes -key server.key -out server.crt -days 3650 -subj /C=RU/ST=Moscow/L=Moscow/O=PiKVM/OU=PiKVM/CN=localhost
1.096 + chown root:kvmd-vnc /etc/kvmd/vnc/ssl/server.crt /etc/kvmd/vnc/ssl/server.key
1.101 + chmod 440 /etc/kvmd/vnc/ssl/server.key
1.103 + chmod 444 /etc/kvmd/vnc/ssl/server.crt
1.105 + chmod 755 /etc/kvmd/vnc/ssl
1.115 sed: can't read /etc/kvmd/nginx/nginx.conf: No such file or directory
------
Dockerfile:13
--------------------
  12 |     
  13 | >>> RUN set -eu; \
  14 | >>>     for unit in man-db.service man-db.timer sshd.service systemd-networkd.service systemd-timesyncd.service systemd-network-generator.service systemd-networkd-wait-online.service systemd-networkd.socket rngd.service systemd-resolved.service watchdog.service getty@tty1.service systemd-random-seed.service kvmd-bootconfig.service eth0.network en.network 99-default.link; \
  15 | >>>     do systemctl mask $unit; \
  16 | >>>     done; \
  17 | >>>     for unit in dbus-org.freedesktop.timesync1.service dbus-org.freedesktop.network1.service dbus-org.freedesktop.resolve1.service; \
  18 | >>>     do systemctl disable $unit; \
  19 | >>>     done; \
  20 | >>>     for unit in cleanup-usb-gadget.service kvmd-tc358743.service switch-to-uyvy.service kvmd-janus.service; \
  21 | >>>     do systemctl enable $unit; \
  22 | >>>     done; \
  23 | >>>     kvmd-gencert --do-the-thing; \
  24 | >>>     kvmd-gencert --do-the-thing --vnc; \
  25 | >>>     sed -i '/PIBOOT/d; /PIPST/d; /PIMSD/d' /etc/fstab; \
  26 | >>>     sed -i 's/stderr/\/var\/log\/nginx\/error.log/' /etc/kvmd/nginx/nginx.conf; \
  27 | >>>     curl -fLSo /usr/local/bin/remove-gadget.sh https://raw.githubusercontent.com/larsks/systemd-usb-gadget/7602009806a4b838663d9db75e5e7f35e131d0c7/remove-gadget.sh; \
  28 | >>>     chmod 755 /usr/local/bin/remove-gadget.sh
  29 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c set -eu;     for unit in man-db.service man-db.timer sshd.service systemd-networkd.service systemd-timesyncd.service systemd-network-generator.service systemd-networkd-wait-online.service systemd-networkd.socket rngd.service systemd-resolved.service watchdog.service getty@tty1.service systemd-random-seed.service kvmd-bootconfig.service eth0.network en.network 99-default.link;     do systemctl mask $unit;     done;     for unit in dbus-org.freedesktop.timesync1.service dbus-org.freedesktop.network1.service dbus-org.freedesktop.resolve1.service;     do systemctl disable $unit;     done;     for unit in cleanup-usb-gadget.service kvmd-tc358743.service switch-to-uyvy.service kvmd-janus.service;     do systemctl enable $unit;     done;     kvmd-gencert --do-the-thing;     kvmd-gencert --do-the-thing --vnc;     sed -i '/PIBOOT/d; /PIPST/d; /PIMSD/d' /etc/fstab;     sed -i 's/stderr/\\/var\\/log\\/nginx\\/error.log/' /etc/kvmd/nginx/nginx.conf;     curl -fLSo /usr/local/bin/remove-gadget.sh https://raw.githubusercontent.com/larsks/systemd-usb-gadget/7602009806a4b838663d9db75e5e7f35e131d0c7/remove-gadget.sh;     chmod 755 /usr/local/bin/remove-gadget.sh" did not complete successfully: exit code: 2
umount: loopmount/boot: no mount point specified.
umount: loopmount: no mount point specified.
rmdir: failed to remove 'loopmount': No such file or directory
losetup: /dev/loop7: detach failed: No such device or address</pre>

**Comment by Prototyped** [comment]
The PiKVM image changed the way nginx was configured and I needed to change the Dockerfile accordingly. [574c044211a9e5e4471b75805f7e9d4d7dcdadf7](https://github.com/Prototyped/pikvm-container/commit/574c044211a9e5e4471b75805f7e9d4d7dcdadf7) fixes this issue.
